### PR TITLE
Issue #517 Added new columns for the VCNT, VL1L2, VAL1L2, and ECNT li…

### LINKED ISSUE #517: Enhance METviewer to plot statistics added to the ECNT, VL1L2, VAL1L2, and VCNT line types introduced in the MET 12.0.0 beta4 development cycle
## Describe the Enhancement ##
Issue dtcenter/METdataio#282 updates the schema to load new wind direction statistics from the VL1L2, VAL1L2, and VCNT line types and new ignorance score statistics to the ECNT line type for MET version 12.0.0 . This issue is to update METviewer to provide access to these new statistics both via the web interface and through the backend XML files, as needed.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/MET#2395
- [x] dtcenter/METdataio#282
- [x] dtcenter/METcalcpy#361
- [x] dtcenter/METviewer#517

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by bikegeek**
…netypes

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

- Created a local docker container for METviewer changes (feature_517_ecnt_vl1l2_val1l2_vcnt)
- Loaded sample data from the MET regression tests for point_stat and ensemble_stat into mariadb in container

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[NA]**

- [x] Do these changes include sufficient testing updates? **[NA]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Do these changes introduce new SonarQube findings? **[No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **by August 22**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METviewer-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

### CODE REVIEW

**Comment by michelleharrold** [comment]
@bikegeek -- I reviewed the PR, and everything I looked at looks good!

Before approving, do we need to be concerned with the failed SonarQube scan (related Duplicated Lines (%) on New Code)? If not, I will approve ASAP!

**Comment by jprestop** [comment]
@michelleharrold and @bikegeek Let's discuss "failed SonarQube scan (related Duplicated Lines (%) on New Code)" at the meeting today.  @bikegeek We'll be sure to update the notes with our discussion in case you're unable to make the meeting.

**Comment by michelleharrold** [comment]
Based on the discussion in the meeting, we do not need to address the code duplication issues, so we are good to go!

**Review by michelleharrold — APPROVED** [review]

**Comment by michelleharrold** [comment]
@bikegeek and @jprestop -- I do not have write access, so my review is not sufficient! Can I be allowed or write access (if not, totally fine, but then we will need another reviewer!)

**Comment by jprestop** [comment]
@michelleharrold Ah! Thanks for letting us know.  Please refresh and give it another try.

**Pull request merged**
