### PR TITLE
Feature 166 develop docker

### LINKED ISSUE #166: Migrate Dockerfile from container-dtc-metviewer to the METviewer repository.
## Describe the Task ##

- Migrate Dockerfile from container-dtc-metviewer (https://github.com/dtcenter/container-dtc-metviewer/tree/master/METviewer) to the METviewer repository itself.
- Once completed, delete the container-dtc-metviewer repository.
- Update the DockerHub METviewer settings (https://hub.docker.com/repository/docker/dtcenter/metviewer/builds) to watch the GitHub METviewer repository.
- Define automated build rules to automatically create/update images for specific branches and retags, similar to the setup for MET (https://hub.docker.com/repository/docker/dtcenter/met/builds/edit).

This setup works much better because anytime the METviewer repo changes (i.e. new development on the develop branch, bugfixes on the master_vX.Y branches, or new release tags), DockerHub will create or rebuild the associated image.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

### PR DESCRIPTION
**Pull request by JohnHalleyGotway**
Adds a docker sub-directory which contains logic for building METviewer from source and the ability to build it via DockerHub. Will also submit a separate PR to merge these same changes into the main_v3.1 branch so that the Docker image from main_v3.1 can serve as the "latest" tag on DockerHub.

### CODE REVIEW

**Comment by TatianaBurek** [comment]
John,
In Dockerfile...
python.env parameter in build.properties needs to  be changed to the new python path ( line #123)
sed -r 's%python.env=.*%python.env=**/usr/local**%g' | \

and line # 131
-Dpython.env.path=**/usr/local/** war \

I follow the instructions and set the variable but the checker ignored it
(base) vpn70-87:docker tatiana$ export METVIEWER_IMAGE_NAME=dtcenter/metviewer

(base) vpn70-87:docker tatiana$ ./check_env.sh && docker-compose up -d
ERROR:
ERROR: METVIEWER_DOCKER_IMAGE defines the image to be run!
ERROR: For example, 'dtcenter/metviewer' from DockerHub or 'metviewer' for a local build.
ERROR:

**Comment by JohnHalleyGotway** [comment]
Tatiana, thanks for pointing out those 2 python paths. I just updated them on this branch.

Also, I see the source of the problem. I'd updated check_env.sh but failed to update the README. So I just fixed that. I switched to METVIEWER_DOCKER_IMAGE instead of METVIEWER_IMAGE_NAME to be more explicit. When running docker build, the build options are METVIEWER_GIT_NAME, METCALCPY_GIT_NAME, and METPLOTPY_GIT_NAME. I figure that it's easy to confuse GIT tags/branches vs DOCKER strings. So I preferred the more explicit naming convention.

**Comment by TatianaBurek** [comment]
I set the variables but failed to run docker-compose:

(base) vpn70-87:docker tatiana$ ./check_env.sh && docker-compose up -d
METVIEWER_DOCKER_IMAGE = dtcenter/metviewer
MYSQL_DIR = /Users/tatiana/Docker/storage
METVIEWER_DATA = /Volumes/d1/tatiana/metviewer
METVIEWER_DIR = /Users/tatiana/Docker/metviewer/metviewer_output/
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[82943] Failed to execute script docker-compose

**Comment by TatianaBurek** [comment]
I set the variables bu failed to run docker-compose:

(base) vpn70-87:docker tatiana$ ./check_env.sh && docker-compose up -d
METVIEWER_DOCKER_IMAGE = dtcenter/metviewer
MYSQL_DIR = /Users/tatiana/Docker/storage
METVIEWER_DATA = /Volumes/d1/tatiana/metviewer
METVIEWER_DIR = /Users/tatiana/Docker/metviewer/metviewer_output/
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[82943] Failed to execute script docker-compose

**Comment by JohnHalleyGotway** [comment]
Running with "dtcenter/metviewer" will not actually work until these PR's are approved and a "dtcenter/metviewer:latest" image is created by DockerHub watching the "main_v3.1" branch of the METviewer GitHub repository.

For testing, please try "export METVIEWER_DOCKER_IMAGE=dtcenter/metviewer:feature_166". I'm retesting this myself now.

**Comment by TatianaBurek** [comment]
I changed the variable value but docker-compose still doesn't work

**Comment by JohnHalleyGotway** [comment]
Tatiana, perhaps you need to make sure that you're pulling the latest version of feature_166 from DockerHub instead of a local version?

```
docker rmi dtcenter/metviewer:feature_166
git clone https://github.com/dtcenter/METviewer
cd METviewer
git checkout feature_166_docker # won't be necessary after PR is approved
cd docker
export METVIEWER_DOCKER_IMAGE=dtcenter/metviewer:feature_166
export MYSQL_DIR=`pwd`/mysql
export METVIEWER_DIR=`pwd`/output
export METVIEWER_DATA=`pwd`/input
mkdir -p $MYSQL_DIR $METVIEWER_DIR $METVIEWER_DATA
./check_env.sh && docker-compose up -d
```

**Review by TatianaBurek — APPROVED** [review]

**Pull request merged**
