### PR TITLE
Feature 199 100 af scorecard

### PR DESCRIPTION
**Pull request by TatianaBurek**
## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer to perform, including the location of input datasets:</br>

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] After merging, should the reviewer **DELETE** the feature branch from GitHub? **[Yes or No]**</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.

### CODE REVIEW

**Comment by lindsayrblank** [comment]
Where can I see the staged html pages? I find it easier to read than the mark up.

**Comment by TatianaBurek** [comment]
Lindsay
What do you mean by "the staged html pages"

**Comment by lindsayrblank** [comment]
I meant a webpage like this http://dtcenter.ucar.edu/met/metviewer/doc/scorecard.html

**Comment by TatianaBurek** [comment]
Here is updated scorecard.html
http://dakota.rap.ucar.edu:8080/metviewer_dev/doc/scorecard.html

**Comment by jprestop** [comment]
Given the update to the documentation, I'm thinking the documentation update should not be made in doc/scorecard.html within this branch, but rather in docs/Users_Guide/scorecard.rst in the task_204_documentation branch.  This underscores the importance of us getting the pull request approved sooner rather than later so that changes can be made in the rst files, which will be in develop once the pull request is approved. Lisa still intends on reviewing Chapters 1-7 soon for grammar/spelling/etc. Tatiana and Tara, have either of you been able to take a look at all of the chapters for accuracy?  If so, please comment in that pull request (https://github.com/dtcenter/METviewer/pull/208).  Lindsay and/or Tatiana, can one of you please migrate the documentation modifications in the task_204_documentation branch?

**Comment by TatianaBurek** [comment]
I looked over, made a few modifications and comments in #208 some time ago.

**Comment by jprestop** [comment]
Great, Tatiana!  Thank you so much! I'll go take a look.  Will you please update the docs/Users_Guide/scorecard.rst in the task_204_documentation branch with the changes you made to scorecard.html in this branch?

**Pull request merged**
